
<div class="panel panel-primary">
	  <div class="panel-heading">
			<h3 class="panel-title"><?php echo ucwords(strtolower($this->_presentRequest->getMetodo())); ?></h3>
	  </div>
	  <div class="panel-body">

	    <form role="form" class="form-horizontal" method="post" enctype="multipart/form-data">

	    	<input type="hidden" name="guardar" value="1" />

	    	<div class="form-group">
				<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Placa: </label>
				<div class="col-xs-12 col-sm-9 col-lg-9">
					<input type="hidden" name="vehiculo" value="<?php if(isset($this->vehiculo)){ echo $this->vehiculo->getId();} ?>"/>
					<input name="placa" class="form-control required" value="<?php if(isset($this->vehiculo)){ echo $this->vehiculo->getPlaca();} ?>" />
				</div>
			</div>

			<div class="form-group">
				<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Frecuencia: </label>
				<div class="col-xs-12 col-sm-9 col-lg-9">
					<?php $frecuencia = ''; ?>
				<?php if(isset($this->dato)){ $frecuencia = $this->dato->getFrecuencia()->getId(); } ?>
					<?php echo $this->combobox("frecuencia", "Seleccione...", $this->frecuencias, $frecuencia, "getId", "getDescripcion", "class='form-control required show-tick' data-live-search='true' ","getDescripcion"); ?>

					
				</div>
			</div>

			<div class="form-group">
				<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Tipo: </label>
				<div class="col-xs-12 col-sm-9 col-lg-9">
					<select name="tipo" class="form-control" required>
                        <option value="">Seleccione... </option>
                        <option value="1" <?php if(isset($this->dato)){ echo $this->dato->getTipo() == 1 ? 'selected' : ''; } ?> >Preventivo</option>
                        <option value="2" <?php if(isset($this->dato)){ echo $this->dato->getTipo() == 2 ? 'selected' : ''; } ?> >Correctivo</option>
                    </select>
				</div>
			</div>


			<div class="form-group">
				<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Fecha: </label>
				<div class="col-xs-12 col-sm-9 col-lg-9">
					<input name="fecha" class="form-control datepicker" data-date-format="dd/mm/yyyy" placeholder="dd/mm/aaaa" value="<?php if(isset($this->dato)){ if($this->dato->getFecha()) { echo $this->dato->getFecha()->format('d/m/Y');} } ?>" />
				</div>
			</div>


			<div class="form-group">
				<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Conductor: </label>
				<div class="col-xs-12 col-sm-9 col-lg-9">
					<input name="conductor" class="form-control required" value="<?php if(isset($this->dato)){ echo $this->dato->getConductor();} ?>" />
				</div>
			</div>

			<div class="form-group">
				<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Revisor: </label>
				<div class="col-xs-12 col-sm-9 col-lg-9">
					<input name="revisor" class="form-control required" value="<?php if(isset($this->dato)){ echo $this->dato->getRevisor();} ?>" />
				</div>
			</div>
			

			<div class="form-group">
                    <label>Observaci&oacute;n:</label>
                   
                    <textarea name="observacion"  class="form-control funciones"  maxlength="400" rows = "4">
                    	<?php if(isset($this->dato)){ echo $this->dato->getObservacion();} ?>
                    </textarea>
                  
                </div>	

			<div class="form-group">
                    <label>Falla:</label>
                   
                    <textarea name="falla"  class="form-control funciones"  maxlength="400" rows = "4">
                    	<?php if(isset($this->dato)){ echo $this->dato->getFalla();} ?>
                    </textarea>
                  
                </div>	

			<div class="form-group">
                    <label>Reparaci&oacute;n:</label>
                   
                    <textarea name="reparacion"  class="form-control funciones"  maxlength="400" rows = "4">
                    	<?php if(isset($this->dato)){ echo $this->dato->getReparacion();} ?>
                    </textarea>
                  
                </div>	
					

<div class="panel-body">
               <div class="form-group">
            <table class="table table-striped table-bordered table-hover" >
				<thead>
					<tr>
						<th>Item</th>
						
						<th class="no-sort" >Ok</th>
						<th class="no-sort" >No Aceptable</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($this->itemfrecuencias as $key => $dato) { ?>
						<tr>
							<td><?php echo $dato->getItem()->getDescripcion(); ?></td>
							
							<td class="text-center" >
								
								<input type="radio" name="radio<?= $dato->getItem()->getId()?>" group="radio<?= $dato->getItem()->getId()?>" class="radio" value="Ok"/>
								
							</td>
							<td class="text-center" >
								<input type="radio" name="radio<?= $dato->getItem()->getId()?>" group="radio<?= $dato->getItem()->getId()?>" class="radio" value="No"/>
								
								
							</td>
						</tr>
					<?php } ?>
				</tbody>
			</table>
			</div>	
 </div>				

			<p class="text-right comentario">
				Los campos marcados con <span class="span">*</span> son obligatorios.
			</p>

			<button type="submit" class="btn btn-primary" ><?php echo ucwords($this->_presentRequest->getMetodo()); ?> </button> 
			

		</form>

	  </div>
</div>

<div class="panel panel-primary">
	  <div class="panel-heading">
			<h3 class="panel-title">Items</h3>
	  </div>
	  <div class="panel-body">

	    <form role="form" class="form-horizontal" method="post" enctype="multipart/form-data">
			
			
		</form>

	  </div>
</div>


<div class="modal fade" id="modal-vacuna">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title">Agregar Vacuna</h4>
			</div>
			<div class="modal-body">
				<form role="form" class="form-horizontal" method="post" enctype="multipart/form-data" action="<?php echo BASE_URL.'mascota/agregarVacuna/' ?>" id="form-vacuna">
					<input type="hidden" name="mascota" value="<?php if(isset($this->dato)){ echo $this->dato->getId();} ?>">
					<div class="form-group">
						<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Vacuna: </label>
						<div class="col-xs-12 col-sm-9 col-lg-9">
							<?php echo $this->combobox("vacuna", "Seleccione...", $this->vacunas, "", "getId", "getDescripcion", "class='form-control required show-tick' data-live-search='true' ","getDescripcion"); ?>
						</div>
					</div>
					<div class="form-group">
						<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Fecha Program: </label>
						<div class="col-xs-12 col-sm-9 col-lg-9">
							<input name="fechaProg" value="" class="form-control fechadatepicker required" data-date-format="dd/mm/yyyy" placeholder="dd/mm/aaaa" />
						</div>
					</div>
					<div class="form-group">
						<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Observacion: </label>
						<div class="col-xs-12 col-sm-9 col-lg-9">
							<textarea class="form-control required" name="observacion"></textarea>
						</div>
					</div>
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
				<button type="button" class="btn btn-primary" id="guardarVacuna" >Guardar</button>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="modal-servicio">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title">Agregar Servicio</h4>
			</div>
			<div class="modal-body">
				<form role="form" class="form-horizontal" method="post" enctype="multipart/form-data" action="<?php echo BASE_URL.'mascota/agregarServicio/' ?>" id="form-servicio">
					<input type="hidden" name="mascota" value="<?php if(isset($this->dato)){ echo $this->dato->getId();} ?>">
					<div class="form-group">
						<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Servicio: </label>
						<div class="col-xs-12 col-sm-9 col-lg-9">
							<?php echo $this->combobox("servicio", "Seleccione...", $this->servicios, "", "getId", "getDescripcion", "class='form-control required show-tick' data-live-search='true' ","getDescripcion"); ?>
						</div>
					</div>
					<div class="form-group">
						<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Fecha Program: </label>
						<div class="col-xs-12 col-sm-9 col-lg-9">
							<input name="fechaProg" value="" class="form-control fechadatepicker required" data-date-format="dd/mm/yyyy" placeholder="dd/mm/aaaa" />
						</div>
					</div>
					<div class="form-group">
						<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Observacion: </label>
						<div class="col-xs-12 col-sm-9 col-lg-9">
							<textarea class="form-control required" name="observacion"></textarea>
						</div>
					</div>
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
				<button type="button" class="btn btn-primary" id="guardarServicio" >Guardar</button>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="modal-asignar-vacuna">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title">Fecha Vacuna</h4>
			</div>
			<div class="modal-body">
				<form role="form" class="form-horizontal" method="post" enctype="multipart/form-data" action="<?php echo BASE_URL.'mascota/asignarVacuna/' ?>" id="form-vacunaF">
					<input type="hidden" name="mascota" value="<?php if(isset($this->dato)){ echo $this->dato->getId();} ?>">
					<input type="hidden" name="vacuna" value="" id="id-vacuna" >
					<div class="form-group">
						<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Fecha: </label>
						<div class="col-xs-12 col-sm-9 col-lg-9">
							<input name="fechaRealVacuna" value="" class="form-control fechadatepicker required" data-date-format="dd/mm/yyyy" placeholder="dd/mm/aaaa" />
						</div>
					</div>
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
				<button type="button" class="btn btn-primary" id="guardarVacunaF" >Guardar</button>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="modal-asignar-servicio">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title">Fecha Servicio</h4>
			</div>
			<div class="modal-body">
				<form role="form" class="form-horizontal" method="post" enctype="multipart/form-data" action="<?php echo BASE_URL.'mascota/asignarServicio/' ?>" id="form-servicioF">
					<input type="hidden" name="mascota" value="<?php if(isset($this->dato)){ echo $this->dato->getId();} ?>">
					<input type="hidden" name="servicio" value="" id="id-servicio" >
					<div class="form-group">
						<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Fecha: </label>
						<div class="col-xs-12 col-sm-9 col-lg-9">
							<input name="fechaRealServicio" value="" class="form-control fechadatepicker required" data-date-format="dd/mm/yyyy" placeholder="dd/mm/aaaa" />
						</div>
					</div>
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
				<button type="button" class="btn btn-primary" id="guardarServicioF" >Guardar</button>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	jQuery(document).ready(function($) {
		$('#vacuna').click(function(event) {
			$('#modal-vacuna').modal();
			$('#guardarVacuna').click(function(event) {
				$('#form-vacuna').submit();
			});		
		});
		$('#servicio').click(function(event) {
			$('#modal-servicio').modal();
			$('#guardarServicio').click(function(event) {
				$('#form-servicio').submit();
			});		
		});
		$(".asignarV").click(function(event) {
			$("#id-vacuna").val($(this).attr('vacuna'));
			$("#modal-asignar-vacuna").modal();
			$('#guardarVacunaF').click(function(event) {
				$('#form-vacunaF').submit();
			});
		});
		$(".asignarS").click(function(event) {
			$("#id-servicio").val($(this).attr('servicio'));
			$("#modal-asignar-servicio").modal();
			$('#guardarServicioF').click(function(event) {
				$('#form-servicioF').submit();
			});
		});
	});
</script>