<?php

namespace Proxies\__CG__\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Vehiculo extends \Entities\Vehiculo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'estado', 'placa', 'nummotor', 'linea', 'numchasis', 'tipocarroceria', 'cilindraje', 'capacidad', 'area', 'servicio', 'modelo', 'numpuertas', 'numlicencia', 'numtarjoperacional', 'fecvenctarjoperacional', 'fecvenctecnomecanico', 'feciniciolabores', 'observacion', 'radio', 'marca', 'tipo', 'combustible', 'mantenimientos');
        }

        return array('__isInitialized__', 'id', 'estado', 'placa', 'nummotor', 'linea', 'numchasis', 'tipocarroceria', 'cilindraje', 'capacidad', 'area', 'servicio', 'modelo', 'numpuertas', 'numlicencia', 'numtarjoperacional', 'fecvenctarjoperacional', 'fecvenctecnomecanico', 'feciniciolabores', 'observacion', 'radio', 'marca', 'tipo', 'combustible', 'mantenimientos');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Vehiculo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', array($estado));

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', array());

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlaca($placa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlaca', array($placa));

        return parent::setPlaca($placa);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlaca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlaca', array());

        return parent::getPlaca();
    }

    /**
     * {@inheritDoc}
     */
    public function setNummotor($nummotor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNummotor', array($nummotor));

        return parent::setNummotor($nummotor);
    }

    /**
     * {@inheritDoc}
     */
    public function getNummotor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNummotor', array());

        return parent::getNummotor();
    }

    /**
     * {@inheritDoc}
     */
    public function setLinea($linea)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLinea', array($linea));

        return parent::setLinea($linea);
    }

    /**
     * {@inheritDoc}
     */
    public function getLinea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLinea', array());

        return parent::getLinea();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumchasis($numchasis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumchasis', array($numchasis));

        return parent::setNumchasis($numchasis);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumchasis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumchasis', array());

        return parent::getNumchasis();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipocarroceria($tipocarroceria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipocarroceria', array($tipocarroceria));

        return parent::setTipocarroceria($tipocarroceria);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipocarroceria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipocarroceria', array());

        return parent::getTipocarroceria();
    }

    /**
     * {@inheritDoc}
     */
    public function setCilindraje($cilindraje)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCilindraje', array($cilindraje));

        return parent::setCilindraje($cilindraje);
    }

    /**
     * {@inheritDoc}
     */
    public function getCilindraje()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCilindraje', array());

        return parent::getCilindraje();
    }

    /**
     * {@inheritDoc}
     */
    public function setCapacidad($capacidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCapacidad', array($capacidad));

        return parent::setCapacidad($capacidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getCapacidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCapacidad', array());

        return parent::getCapacidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setArea($area)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArea', array($area));

        return parent::setArea($area);
    }

    /**
     * {@inheritDoc}
     */
    public function getArea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArea', array());

        return parent::getArea();
    }

    /**
     * {@inheritDoc}
     */
    public function setServicio($servicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setServicio', array($servicio));

        return parent::setServicio($servicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getServicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServicio', array());

        return parent::getServicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setModelo($modelo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModelo', array($modelo));

        return parent::setModelo($modelo);
    }

    /**
     * {@inheritDoc}
     */
    public function getModelo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModelo', array());

        return parent::getModelo();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumpuertas($numpuertas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumpuertas', array($numpuertas));

        return parent::setNumpuertas($numpuertas);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumpuertas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumpuertas', array());

        return parent::getNumpuertas();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumlicencia($numlicencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumlicencia', array($numlicencia));

        return parent::setNumlicencia($numlicencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumlicencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumlicencia', array());

        return parent::getNumlicencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumtarjoperacional($numtarjoperacional)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumtarjoperacional', array($numtarjoperacional));

        return parent::setNumtarjoperacional($numtarjoperacional);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumtarjoperacional()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumtarjoperacional', array());

        return parent::getNumtarjoperacional();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecvenctarjoperacional($fecvenctarjoperacional)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecvenctarjoperacional', array($fecvenctarjoperacional));

        return parent::setFecvenctarjoperacional($fecvenctarjoperacional);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecvenctarjoperacional()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecvenctarjoperacional', array());

        return parent::getFecvenctarjoperacional();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecvenctecnomecanico($fecvenctecnomecanico)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecvenctecnomecanico', array($fecvenctecnomecanico));

        return parent::setFecvenctecnomecanico($fecvenctecnomecanico);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecvenctecnomecanico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecvenctecnomecanico', array());

        return parent::getFecvenctecnomecanico();
    }

    /**
     * {@inheritDoc}
     */
    public function setFeciniciolabores($feciniciolabores)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFeciniciolabores', array($feciniciolabores));

        return parent::setFeciniciolabores($feciniciolabores);
    }

    /**
     * {@inheritDoc}
     */
    public function getFeciniciolabores()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeciniciolabores', array());

        return parent::getFeciniciolabores();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacion($observacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacion', array($observacion));

        return parent::setObservacion($observacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacion', array());

        return parent::getObservacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setRadio($radio = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRadio', array($radio));

        return parent::setRadio($radio);
    }

    /**
     * {@inheritDoc}
     */
    public function getRadio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRadio', array());

        return parent::getRadio();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarca($marca = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarca', array($marca));

        return parent::setMarca($marca);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarca', array());

        return parent::getMarca();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo($tipo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', array($tipo));

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', array());

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCombustible($combustible = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCombustible', array($combustible));

        return parent::setCombustible($combustible);
    }

    /**
     * {@inheritDoc}
     */
    public function getCombustible()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCombustible', array());

        return parent::getCombustible();
    }

    /**
     * {@inheritDoc}
     */
    public function getMantenimientos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMantenimientos', array());

        return parent::getMantenimientos();
    }

}
